# Use postgres/example user/password credentials
version: '3.8'

services:

  web:
    container_name: web
    build:
      context: .
    restart: always
    ports:
      - 8080:8080
  db:
    container_name: postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
      POSTGRES_DB: trades
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  db:
